name: Upload package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/JeremTech/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release McVersionsLib
      - name: Create the package
        run: dotnet pack --configuration Release McVersionsLib
      - name: Publish the package to GPR
        run: dotnet nuget push McVersionsLib/bin/Release/*.nupkg
